# Generated by Django 2.1.7 on 2019-02-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('review_rating', models.TextField(blank=True, null=True)),
                ('review_count', models.DateTimeField(auto_now=True)),
                ('product_id', models.TextField()),
                ('url', models.TextField()),
                ('is_cloudary_image', models.BooleanField(default=True)),
                ('sub_title', models.TextField()),
                ('price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wishlist post',
                'verbose_name_plural': 'Wishlists posts',
            },
        ),
    ]
