# Generated by Django 2.1.7 on 2019-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='review_count',
            field=models.TextField(blank=True, null=True),
        ),
    ]
